### ISSUE TITLE
Bringing back the checkmarks.

### ISSUE THREAD

**Issue by iluikatl** [khanhas/spicetify-cli#111]
A most polemic change was when the checkmarks where replaced for hearts in a recent big update. In the same vein, the icon for adding a song was a plus sign, as opposed to the current outline of a heart icon. 

How can I replace the hearts for checkmarks and the plus sign? 

I asked on reddit and somebody shared the next bit of css, but it's not working for me. 

/* add to saved icon */
.nft-enabled .tl-save .button::before {
    content: "+" !important;
}

/* icon when added */
.nft-enabled .added .button .nowplaying-add-button .button-icon-only .button-add::before {
    content: "✓" !important;
}

**Comment by khanhas** [comment]
```css
.spoticon-heart-16::before {
    content: "\f138";
}
.spoticon-heart-active-16::before {
  content: "\f10a";
}
```

**Comment by iluikatl** [comment]
I must be missing something. If I edit that into the css using devtools, I don't get any of the changes. Same if I edit the user.css file, in which I'm just pasting in your code at the end. Then running the update command and reloading in Spotify.

**Comment by khanhas** [comment]
Huh, my bad, I thought you were talking about heart buttons in playlists and albums.

This should changes heart button in player bar:
```css
.nft-enabled .view-player .now-playing-container .nowplaying-add-button.added:before {
    content: "\f10a";
}
.nft-enabled .view-player .now-playing-container .nowplaying-add-button:before {
        content: "\f138";
}
```

Also they have different class names all over the place. Just use inspect tool, point to the icon button. Their CSS selectors should contain class name and `:before` tag.
