### ISSUE TITLE
Any possible ways to remove color gradients?

### ISSUE THREAD

**Issue by parromtra** [khanhas/spicetify-cli#1184]
Spotify version: 1.1.70.610.g4585142b-a
Spicetify version:  2.7.1
Windows 10 21H1

Hey guys,

1. Since some of recent Spotify updates I can no longer remove these annoying picture-based color gradients at the playlists' header. I presume it's because of new dynamic classes system. Maybe I'm wrong. Do you know any solution for this?
2.  Another annoying thing is the unnecessary gradient divider above my playlists on the left. Could I somehow get rid of it without changing "shadows" color?
3. Semi-transparent min-max-close buttons imho would be looking better if they are of the same color as the main bg. But I can't find what to edit to change their color and opacity

Please advise.

✔️ Expected result

![sp 1](https://user-images.githubusercontent.com/88559257/138376305-74d8830d-ec91-4e03-988b-77a037859c7a.jpg)

❌ Actual result

![sp 2](https://user-images.githubusercontent.com/88559257/138375287-3fd97ffe-6e01-4242-b3d2-150b301ba9a0.jpg)

**Comment by itsmeow** [comment]
Here is the CSS you are looking for. You can add this to an existing theme or make one.

```css
.main-entityHeader-backgroundColor {
    background-color: inherit !important;
}
.main-actionBarBackground-background {
    background-color: inherit !important;
}
```

This one is optional if you want to change the top control bar color when it's scrolled. You change inherit to a more fitting color, since by default this will end up being transparent and look kind of weird.
```css
.main-topBar-background {
    background-color: inherit !important;
}
```
