### ISSUE TITLE
Persistent stock css.

### ISSUE THREAD

**Issue by akshat46** [khanhas/spicetify-cli#47]
I am on Ubuntu 18.04. Everything went well with fresh installs of spotify(from .deb package as listed in the wiki) and spicetify. 
When I tried to change padding for `Header__content-wrapper` in `~/.config/spicetify/Themes/user.css` some of the elements reverted to stock css. Specifically the header background's gradient and the header title style. 

![image](https://user-images.githubusercontent.com/7402043/63188219-aa913500-c015-11e9-99e3-f401f8360b5f.png)

I have tried deleting spicetify config folder, and reinstalling spotify, and following the steps in "Basic Usage" section in wiki again but it didn't work. Also tried following: 
```css
/* ~/.config/spicetify/Themes/user.css */
.Header__background .Header__background-color{
    background-image: none !important;
}
```
in but it didn't work.

**Comment by khanhas** [comment]
This is CSS problem, it has nothing to do with Spicetify. You can try these kind of questions on Spectrum first, people with CSS knowledge can help you.
Anyway, just put these in your CSS:
```css
.Header__background-color {
    background-color: var(--modspotify_main_bg) !important;
    background-image: none !important;
}
```
```
