### ISSUE TITLE
Search bar hidden when using inject_css 0 and replace_colors 0

### ISSUE THREAD

**Issue by theredbaron05** [khanhas/spicetify-cli#590]

**Comment by theredbaron05** [comment]
the search bar still works and is in the same place but you can't see what you are typing.

**Comment by khanhas** [comment]
Yeah, it's very weird bug and I tried to investigate it before but no cigar. Please just make a new theme folder, put this in file `user.css`:
```css
/* Topbar visibility bug */
.main-topBar-topbarContent:not(.main-topBar-topbarContentFadeIn)>* {
    opacity: unset !important;
}
.main-entityHeader-topbarContent:not(.main-entityHeader-topbarContentFadeIn)>* {
    opacity: 0 !important;
}
```
Then turn on `inject_css` and run `spicetify apply`.
