### ISSUE TITLE
New lyrics-plus app doesn't show musixmatch synced lyrics

### ISSUE THREAD

**Issue by impervius** [khanhas/spicetify-cli#653]
Only the Genius tab works, other tabs show `(*_*)`. The popupLyrics.js extension does show lyrics (from MusixMatch) for some songs, and the Synced tab in lyrics-plus doesn't show lyrics for any song. I updated the MusixMatch token to my token.

![image](https://user-images.githubusercontent.com/63152795/119218151-92eab880-bae7-11eb-9a20-89c309986712.png)

(I'm not sure that this exceptions is the causing this bug)
![image](https://user-images.githubusercontent.com/63152795/119218054-db55a680-bae6-11eb-95e9-a86eb3c4ff19.png)
```
Uncaught (in promise) TypeError: Cannot read property '1' of null
    at Object.getNote (spicetify-routes-lyrics-plus.js:597)
    at spicetify-routes-lyrics-plus.js:1191
    at Ia (vendor~xpui.js:29)
    at Ps (vendor~xpui.js:29)
    at t.unstable_runWithPriority (vendor~xpui.js:29)
    at hi (vendor~xpui.js:29)
    at Rs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at x (vendor~xpui.js:29)
    at F (vendor~xpui.js:29)
```

```
➜ spicetify --version
2.2.3

➜ spotify --version
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
Spotify version 1.1.56.595.g2d2da0de, Copyright (c) 2021, Spotify Ltd
````
```
[Setting]
current_theme           = SpicetifyDefault
color_scheme            = nord-dark
overwrite_assets        = 0
spotify_launch_flags    =
spotify_path            = /opt/spotify
inject_css              = 1
replace_colors          = 1
check_spicetify_upgrade = 0
prefs_path              = /home/anon/.config/spotify/prefs

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions  = shuffle+.js|popupLyrics.js
custom_apps = lyrics-plus

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.56.595.g2d2da0de
```

**Comment by khanhas** [comment]
Can you right click at Synced tab to lock in and play that track again? Switch to another track then switch back

**Comment by impervius** [comment]
Tried it, the Synced tab is loading for a fraction of a second and then returns to the `(*_*)` screen. The console tab in the devtools doesn't print any error though (that why I wrote that I'm not sure that I'm not sure the attached exception is related).

**Comment by khanhas** [comment]
Oh damn, found the problem. I changed config name using refactor tool, though it would change name in other files too. 
Just overwrite the original one this file:
https://raw.githubusercontent.com/khanhas/spicetify-cli/master/CustomApps/lyrics-plus/ProviderMusixmatch.js
Run this to know where the app located
```
spicetify path -a lyrics-plus
```
After overwriting, run `spicetify apply`.

**Comment by khanhas** [comment]
Also weird that `netease` should kick in if musixmatch lyrics isn't found.

**Comment by impervius** [comment]
Working after the proposed edit, Thanks!

Regarding `netease`, I don't know how it works and what tracks it has, but if you'd like me to check stuff, I'd be happy to help. Not closing this issue in case you would like me to check the `netease` thing.

**Comment by khanhas** [comment]
i mean I played  the same track before edited the js file. Provider Netease had that track lyrics and worked fine.

**Comment by Chikorit** [comment]
Hello. Thank you for this. Netease has more lyrics than musicxmatch, it's better. So does it come out by default in synced I leave in that way.

Just a question, is it possible to reduce the size of the lyrics? They are too big and if I use the old UI if they come out in the correct size for me.

Thanks

**Comment by khanhas** [comment]
```css

.lyrics-lyricsContainer-SyncedLyrics .lyrics-lyricsContainer-LyricsLine {
    --lyrics-line-height: 36px;
    font-size: 32px;
    font-weight: 700;
    letter-spacing: -.04em;
    line-height: 36px
}

@media(min-width:1024px) {

    .lyrics-lyricsContainer-SyncedLyrics .lyrics-lyricsContainer-LyricsLine {
        --lyrics-line-height: 48px;
        font-size: 48px;
        font-weight: 700;
        letter-spacing: -.04em;
        line-height: 48px
    }
}

@media(min-width:1280px) {

    .lyrics-lyricsContainer-SyncedLyrics .lyrics-lyricsContainer-LyricsLine {
        --lyrics-line-height: 72px;
        font-size: 72px;
        font-weight: 900;
        letter-spacing: -.04em;
        line-height: 72px
    }
}
```
Add this to your user.css and change font-size accordingly to window size.
