### ISSUE TITLE
Can't update class

### ISSUE THREAD

**Issue by MacaroniNuggets** [khanhas/spicetify-cli#79]
Specifically, I can't update `.TableRow--is-selected`, which is defined in zlink.css.
In my user.css I wrote:
```css
.TableRow--is-selected {
        background-color: none !important;
}
```
According to what I know about CSS, this should be right.  Have I done this wrong, or can we not edit elements of zlink.css?
