### ISSUE TITLE
I want to apply a font as @font-face

### ISSUE THREAD

**Issue by quiple** [khanhas/spicetify-cli#895]
## ℹ Computer information

- Spotify version: `1.1.62.583.gdac868ed`
- Spicetify version: `2.5.0`

## 📝 Provide detailed reproduction steps (if any)

1. Add `@font-face` rules in `user.css`.
```css
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-ultralight.otf");font-weight:100}
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-extralight.otf");font-weight:200}
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-light.otf");font-weight:300}
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-regular.otf");font-weight:400}
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-medium.otf");font-weight:500}
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-bold.otf");font-weight:700}
@font-face {font-family:'axisq';src:url("file:///D:/font/axis/axisstd-heavy.otf");font-weight:900}

* {
  box-shadow: none !important;
  font-family: 'SF UI Text', 'axisq', sans-serif;
  font-feature-settings: 'palt';
  letter-spacing: 0 !important;
}
```
2. Save and `spicetify apply`.
```
PS C:\Users\User> spicetify apply
spicetify v2.5.0
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
success Spotify is spiced up!
```
3. But it does not apply to the output. Is there something I'm missing out on? or Is there no way to apply a font as @font-face in Spicetify?

### ✔️ Expected result
The font I want should be applied.

### ❌ Actual result
The font I want is not applied.
